[target.xtensa-esp32s2-none-elf]
runner = "espflash flash --chip=esp32s2 --before=no-reset --no-stub --port=/dev/ttyACM1"

[env]
ESP_LOG="INFO"
EMBASSY_EXECUTOR_TASK_ARENA_SIZE="8192"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s2-none-elf"

[unstable]
build-std = ["alloc", "core"]
